# Generated by Django 6.0.4 on 2026-04-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Sem categoria', 'Uncategorized'), ('Desatenção', 'Inattention'), ('Hiperatividade', 'Hyperactivity'), ('Impulsividade', 'Impulsivity'), ('Interação social', 'Social interaction'), ('Comportamento', 'Behavior')], default='Sem categoria', max_length=50)),
                ('question', models.CharField(max_length=200)),
                ('type_user', models.CharField(choices=[('Para mim', 'for you'), ('Para parente', 'for parents'), ('Para aluno', 'for students')], max_length=50)),
            ],
            options={
                'verbose_name': 'Questão do teste',
                'verbose_name_plural': 'Questões do teste',
                'db_table': 'questions_test',
            },
        ),
    ]
