# Generated by Django 6.0.4 on 2026-05-07 20:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register_login_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, default='Não quero comentar')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='register_login_app.expert')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='register_login_app.patient')),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
                'db_table': 'testimonials',
            },
        ),
    ]
