# Generated by Django 6.0.4 on 2026-05-12 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_login_app', '0001_initial'),
        ('relacion_user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='register_login_app.expert'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='register_login_app.patient'),
        ),
        migrations.CreateModel(
            name='Consult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('link', models.URLField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDENTE'), ('HELD', 'REALIZADA'), ('CANCELED', 'CANCELADA')], default='PENDING', max_length=50)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='register_login_app.expert')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='register_login_app.patient')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'db_table': 'consult',
            },
        ),
        migrations.AddField(
            model_name='testimonial',
            name='consult',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='relacion_user_app.consult'),
            preserve_default=False,
        ),
    ]
