# Generated by Django 6.0.3 on 2026-04-18 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('initials', models.CharField(max_length=6)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Especialidade',
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fone', models.CharField(max_length=20)),
                ('date_birth', models.DateField()),
                ('photo_perfil', models.ImageField(blank=True, null=True, upload_to='photo_profile/%Y/%m/%d/')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pacientes',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='Experts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fone', models.CharField(max_length=20)),
                ('date_birth', models.DateField()),
                ('photo_perfil', models.ImageField(blank=True, null=True, upload_to='photo_profile/%Y/%m/%d/')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('num_registration', models.CharField(max_length=50)),
                ('verification', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('specialties', models.ManyToManyField(related_name='experts', to='register_login_app.specialties')),
            ],
            options={
                'verbose_name': 'Especialista',
                'verbose_name_plural': 'Especialistas',
                'ordering': ['-create_date'],
            },
        ),
    ]
