# Generated by Django 6.0.4 on 2026-05-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipsCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='photo_tips/')),
                ('alt', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Card Dica',
                'verbose_name_plural': 'Cards Dicas',
                'db_table': 'tips_card',
            },
        ),
    ]
