# Generated by Django 6.0.4 on 2026-05-07 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nome da categoria')),
                ('icon_class', models.CharField(help_text='icone do bootstrap', max_length=50)),
            ],
            options={
                'verbose_name': 'Categoria da pertunta',
                'verbose_name_plural': 'Categorias das pertuntas',
                'db_table': 'category_faq',
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='pergunta')),
                ('answer', models.TextField(verbose_name='resposta')),
                ('list_answer', models.TextField(help_text='a cada linha e item da lista')),
                ('useful', models.PositiveIntegerField(default=0)),
                ('not_useful', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(help_text='categoria da pergunta', on_delete=django.db.models.deletion.CASCADE, to='faq_app.categoryfaq')),
            ],
            options={
                'verbose_name': 'Pergunta e resposta',
                'verbose_name_plural': 'Perguntas e respostas',
                'db_table': 'question_answer',
            },
        ),
    ]
