# Generated by Django 6.0.4 on 2026-05-24 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='category',
            field=models.ForeignKey(help_text='categoria da pergunta', on_delete=django.db.models.deletion.CASCADE, related_name='questionanswer', to='faq_app.categoryfaq'),
        ),
    ]
