# Generated by Django 6.0.4 on 2026-05-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq_app', '0002_alter_questionanswer_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='list_answer',
            field=models.TextField(blank=True, help_text='a cada linha e item da lista', null=True),
        ),
    ]
